// Generated by CoffeeScript 1.7.1
(function() {
  require(["bower_components/jsoneditor/jsoneditor-min", "cssconv"], function(json, css) {
    "use strict";
    return $(function() {
      var bh, e, style, update, x;
      style = $("#styleName").val();
      x = $("<div>");
      update = function() {
        $("#jsonBody").val(e.getText());
        return $("pre#stylesheet").text(css.rules(e.get()));
      };
      e = new json.JSONEditor(x[0], {
        modes: ['tree', 'code'],
        change: update
      });
      json = JSON.parse($("input#styles").val())[$("input#styleName").val()];
      bh = function(style) {
        e.set(json);
        return update();
      };
      bh(style);
      $("pre#stylesheet").text(css.rules(json));
      $("p#jsonEditor").append(x);
      return $("form#parseCson").on("submit", function(evt) {
        var data, req;
        evt.preventDefault();
        data = {
          body: $(this).find('textarea[name="body"]').val()
        };
        req = $.ajax($("#appRoot").val() + "/to/cson", {
          data: data,
          type: "post",
          dataType: 'json'
        });
        req.done(function(data) {
          e.set(data);
          return update();
        });
        return req.fail(function(w, msg) {
          return alert(msg);
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=app.map
