// Generated by CoffeeScript 1.7.1
(function() {
  require(["bower_components/jsoneditor/jsoneditor-min", "cssconv"], function(json, css) {
    return $(function() {
      var e, update, x;
      x = $("<div>");
      update = function() {
        return $("pre#stylesheet").text(css.rules(e.get()));
      };
      e = new json.JSONEditor(x[0], {
        modes: ['tree', 'code'],
        change: update
      });
      json = JSON.parse($("input#styles").val())["default"];
      e.set(json);
      $("pre#stylesheet").text(css.rules(json));
      $("p#jsonEditor").append(x);
      return $("form#styleEditor").on("submit", function(evt) {
        var data, req;
        evt.preventDefault();
        data = {
          body: e.getText(),
          file: $("input#styleName").val()
        };
        req = $.ajax("", {
          type: "post",
          data: data
        });
        req.done(function(data) {
          return alert(data);
        });
        return req.fail(function(self, data) {
          e.set(json);
          update();
          return alert(data);
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=app.map
