// Generated by CoffeeScript 1.7.1
(function() {
  var requirejs;

  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require
  });

  requirejs(['cssconv'], function(css) {
    return console.log(css.rules([[["h1"], [["font-family", ["Arial", "sans-serif"]]]]]));
  });

}).call(this);

//# sourceMappingURL=test_cssconv.map
